#ifndef QNOTIFICATIONGLOBAL_H
#define QNOTIFICATIONGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_NOTIFICATION_LIB)
#    define Q_NOTIFICATION_EXPORT Q_DECL_EXPORT
#  else
#    define Q_NOTIFICATION_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_NOTIFICATION_EXPORT
#endif

QT_END_NAMESPACE

#endif
