#ifndef QPUSHNOTIFICATIONGLOBAL_H
#define QPUSHNOTIFICATIONGLOBAL_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_PUSHNOTIFICATION_LIB)
#    define Q_PUSHNOTIFICATION_EXPORT Q_DECL_EXPORT
#  else
#    define Q_PUSHNOTIFICATION_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_PUSHNOTIFICATION_EXPORT
#endif

QT_END_NAMESPACE

#endif
